name: appimage-release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get appimagetool
      run: |
        set -x
        wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O appimagetool.AppImage
        chmod +x appimagetool.AppImage
        pwd; ls -lah

    - name: Make Appimage
      shell: bash
      run: |
        set -x

        P_URL="https://download-cdn.jetbrains.com/python/pycharm-community-2021.1.2.tar.gz"
        #P_URL="https://download-cdn.jetbrains.com/python/pycharm-community-2024.1.tar.gz"

        P_NAME="$(echo "PyCharm-community")"
        P_FILENAME="$(echo $P_URL | cut -d/ -f5)"
        P_VERSION="$(echo $P_FILENAME | cut -d- -f3 | sed 's/\.[^.]*$//' | sed 's/\.[^.]*$//')"
        WORKDIR="workdir"

        mkdir "$WORKDIR"
        wget -nv $P_URL
        tar xf $P_FILENAME -C "$WORKDIR/"

        cat > "$WORKDIR/AppRun" << EOF
        #!/bin/bash
        HERE="\$(dirname "\$(readlink -f "\${0}")")"
        #------------------------------

        MAIN="\$HERE/pycharm-community-${P_VERSION}/bin/pycharm.sh"

        export PATH="\$HERE/pycharm-community-${P_VERSION}/bin":\$PATH
        "\$MAIN" "\$@" | cat

        EOF
        chmod +x $WORKDIR/AppRun

        cat > "$WORKDIR/PyCharm.desktop" << EOF
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=PyCharm Community Edition
        Icon=pycharm
        Exec=AppRun
        Comment=Python IDE for Professional Developers
        Categories=Development;IDE;
        Terminal=false
        StartupWMClass=jetbrains-pycharm-ce

        EOF

        #cp resource/pycharm.png "$WORKDIR"
        ls "$WORKDIR/bin/"
        cp "$WORKDIR/bin/pycharm.png" "$WORKDIR"

        mv README.md $WORKDIR

        pwd; ls -lah
        ls -lah $WORKDIR

        export ARCH=x86_64; ./appimagetool.AppImage -v $WORKDIR $P_NAME-v${P_VERSION}-${ARCH}-1_JB.AppImage

        md5sum $P_NAME-v${P_VERSION}-${ARCH}-1_JB.AppImage > $P_NAME-v${P_VERSION}-${ARCH}-1_JB.AppImage.md5
        pwd; ls -lah

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "PyCharm*.AppImage; PyCharm*.AppImage.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
          default_release_name: "PyCharm-community V in AppImage"
